cleanup; more generic code; more robust

diff --git a/ak b/ak
--- a/ak
+++ b/ak
@@ -4,23 +4,39 @@
 # will give you shortcuts to main project commands.
 
 IMAGE=${IMAGE:="akretion/voodoo"}
+NAME=${NAME:="voodoo-${PWD##*/}"}
 PORT=${PORT:="8069"}
 POLLING_PORT=${POLLING_PORT:="8072"}
-SSH_USER=${SSH_USER:="api"}
 SERVER=${SERVER:="$2.akretion.com"}
+POSTGRESQL_DB=${POSTGRESQL_DB:="db"}
+POSTGRESQL_DATA=${POSTGRESQL_DATA:="/workspace/.db"}
+WORKDIR=${WORKDIR:="/workspace"}
+START_OPTIONS=${START_OPTIONS:="-ti"}
+CONTAINER_FILE=${CONTAINER_DIR:="/.devstep"}
+PIP_DIR=${PIP_DIR:="/.devstep/.pip_packages"}
+SHARED_EGGS_DIR=${SHARED_EGGS_DIR:="/.devstep/addons/voodoo/host_eggs"}
+IMAGE_EGGS_DIR=${IMAGE_EGGS_DIR:="/.devstep/addons/voodoo/eggs"}
+SHARED_ODOO_DIR=${SHARED_ODOO_DIR:="/.devstep/addons/voodoo/odoo"}
+DOCKER_USER=${DOCKER_USER:="developer"}
+DOCKER_RM=${DOCKER_RM:="true"}
+SSH_USER=${SSH_USER:="api"}
+BUILDOUT=${BUILDOUT:="buildout.dev.cfg"}
 
 
-if [ ! -d /.devstep ]; then
-  # we are out of the container, this is the bash equivalent of Vagrant with the Docker provider:
-  in_container=false
-  if [[ -z $1 || $1 == "up" || $1 == "run" || $1 == "build" || $1 == "debug" || $1 == "console" && -z $2 || $1 == "psql" || $1 == "help" ]]; then
+# *****************************************************************************
+if [ ! -d "$CONTAINER_DIR" ]; then
+  # we are outside of the container,
+  # this is the bash equivalent of Vagrant with the Docker provider
 
-    if [[ ! -z "$(git remote -v | grep origin | grep "github.com/akretion/voodoo")" ]]; then
-      git remote remove origin # avoid Akretion team to re-push accidentally on repo
+  if [[ -z $1 || $1 == "up" || $1 == "run" || $1 == "build" || $1 == "debug" || \
+     $1 == "console" && -z $2 || $1 == "psql" || $1 == "help" && -z $2 ]]; then
+
+    if [[ ! -z "$(git remote -v | grep "github.com/akretion/voodoo")" ]]; then
+      git remote remove origin # avoid push to wrong remote
     fi
 
     if [[ ! $(docker images | grep "$IMAGE") ]]; then
-      echo "Socker $IMAGE not found!"
+      echo "Docker $IMAGE not found!"
       echo "Warning! We will now download 1.6 GB (but only once)"
       docker pull ubuntu:trusty
       docker pull fgrehm/devstep:v0.1.0
@@ -28,25 +44,31 @@ if [ ! -d /.devstep ]; then
     fi
 
 
-    VOLUMES="-v $PWD:/workspace"
-    odoo_dir=$(sed -n 's/^odoo-directory *= *\([^ ]*.*\)/\1/p' < buildout.dev.cfg)
+    VOLUMES="-v $PWD:$WORKDIR"
+    odoo_dir=$(sed -n 's/^odoo-directory *= *\([^ ]*.*\)/\1/p' < $BUILDOUT)
     if [ ! -z "$odoo_dir" ]; then
       eval odoo_dir=$odoo_dir        # eval ~
       odoo_dir=$(dirname "$odoo_dir/fake") # expands to absolute path
       echo "assuming shared Odoo directory: $odoo_dir"
-      VOLUMES="$VOLUMES -v $odoo_dir:/.devstep/addons/voodoo/odoo"
+      VOLUMES="$VOLUMES -v $odoo_dir:$SHARED_ODOO_DIR"
     fi
-    eggs_dir=$(sed -n 's/^eggs-directory *= *\([^ ]*.*\)/\1/p' < buildout.dev.cfg)
+    eggs_dir=$(sed -n 's/^eggs-directory *= *\([^ ]*.*\)/\1/p' < $BUILDOUT)
     if [ ! -z "$eggs_dir" ]; then
       eval eggs_dir=$eggs_dir        # eval ~
       eggs_dir=$(dirname "$eggs_dir/fake") # expands to absolute path
       echo "assuming shared eggs directory: $eggs_dir"
       [ ! -d "$eggs_dir" ] &&  mkdir -p "$eggs_dir"
-      VOLUMES="$VOLUMES -v $eggs_dir:/.devstep/addons/voodoo/host_eggs"
+      VOLUMES="$VOLUMES -v $eggs_dir:$SHARED_EGGS_DIR"
     fi
     echo "Entering Docker warp zone with shared volumes:"
     echo "$VOLUMES"
 
+
+    containers=$(docker ps -a | grep " $NAME " | awk '{ print $1 }') || true
+    if [ ! -z $containers ]; then
+      echo "killing existing container(s)"
+      docker rm -v -f $containers 2>/dev/null || true
+    fi
 
     nc -z 127.0.0.1 "$PORT"
     while [ $? = 0 ]
@@ -59,75 +81,63 @@ if [ ! -d /.devstep ]; then
     echo "Odoo will run on port $PORT"
     PORTS="-p $PORT:8069 -p $POLLING_PORT:8072"
 
-
-    docker run -ti -e POSTGRESQL_DB=db -e POSTGRESQL_DATA=/workspace/.db --rm=true --name voodoo-${PWD##*/} $PORTS $VOLUMES -w /workspace $IMAGE -- /bin/bash -c "'/workspace/ak $@'"
-    exit
+    docker run $START_OPTIONS -e POSTGRESQL_DB="$POSTGRESQL_DB" \
+               -e POSTGRESQL_DATA="$POSTGRESQL_DATA" \
+               -u $DOCKER_USER \
+               --rm=$DOCKER_RM --name $NAME $PORTS $VOLUMES -w "$WORKDIR" $IMAGE \
+               -- /bin/bash -c "'$WORKDIR/ak $@'"
 
   else
-    api=true
+    exec ssh "$SSH_USER@$SERVER" "$@"
   fi
 
 
-else # when we are inside the container
-  in_container=true
-  export PYTHONPATH=$PYTHONPATH:/.devstep/.pip_packages
-  eggs_dir=/.devstep/addons/voodoo/host_eggs
-  if [ -d $eggs_dir ]; then
-    if [ ! $(ls "$eggs_dir" | grep reportlab) ]; then
+# *****************************************************************************
+else # when we are inside of the container
+
+  export PYTHONPATH=$PYTHONPATH:$PIP_DIR
+  if [ ! -d $PIP_DIR ]; then
+    # NOTE sadly we cannot persit .pip_packages inside /workspace
+    # because of this pip bug https://github.com/pypa/pip/issues/1489
+    [ ! $(cat requirements.txt | grep -v "^#" | grep "[a-z]" | wc -l) = "0" ] && \
+    echo "installing requirements.txt with pip" && \
+    pip install -r requirements.txt --target=$PIP_DIR
+  fi
+
+  if [ -d $SHARED_EGGS_DIR ]; then
+    eggs_dir="$SHARED_EGGS_DIR"
+    if [ ! $(ls "$SHARED_EGGS_DIR" | grep reportlab) ]; then
       echo "initializing shared host eggs directory from Docker image"
-      sudo chown -R developer $eggs_dir
-      cp /.devstep/addons/voodoo/eggs/. $eggs_dir -R
+      sudo chown -R $DOCKER_USER $eggs_dir
+      cp "$IMAGE_EGGS_DIR"/. $eggs_dir -R
     fi
   else
-    eggs_dir=/.devstep/addons/voodoo/eggs
+    eggs_dir="eggs"
   fi
 
   if [ ! -f bin/buildout ]; then 
     echo "Bootstrapping Buildout..."
     cd /tmp
-    cp /workspace/buildout.cfg .
+    cp "$WORKDIR/buildout.cfg" .
     wget https://raw.github.com/buildout/buildout/master/bootstrap/bootstrap.py
     python bootstrap.py --allow-site-packages
-    cp -rf bin /workspace/bin
-    cd /workspace
-  fi
-
-  if [ ! -d /.devstep/.pip_packages ]; then
-    PROJECT_PIP_DIR=/.devstep/.pip_packages
-    # NOTE sadly we cannot persit .pip_packages inside /workspace because of this pip bug https://github.com/pypa/pip/issues/1489
-    # TODO see if Devstep has a better solution for this
-    [ ! $(cat requirements.txt | grep -v "^#" | grep "[a-z]" | wc -l) = "0" ] && \
-    echo "installing requirements.txt with pip" && \
-    pip install -r requirements.txt --target=$PROJECT_PIP_DIR
-    export PYTHONPATH=$PYTHONPATH:$PROJECT_PIP_DIR
+    cp -rf bin "$WORKDIR/bin"
+    cd "$WORKDIR"
   fi
 
   [ ! -d parts ] && mkdir parts
-  [ -f /.devstep/addons/voodoo/odoo/setup.py ] && [ ! -f parts/odoo/setup.py ] && ln -s /.devstep/addons/voodoo/odoo parts/odoo
+
+  if [ -f "$SHARED_ODOO_DIR"/setup.py ]; then
+    [ ! -f parts/odoo/setup.py ] && ln -s "$SHARED_ODOO_DIR" parts/odoo
+  fi
 
 
-  case $1 in
-
-  wait_postgres)
-    [ -f /.devstep/log/postgresql.log ] && r=$(grep "ready to accept connections" /.devstep/log/postgresql.log)
-    [ -z "$r" ] && echo "waiting for Postgresql embedded server to start..."
-    while [ -z "$r" ]
-    do
-      sleep 0.1
-      [ -f  /.devstep/log/postgresql.log ] && r=$(grep "ready to accept connections" /.devstep/log/postgresql.log)
-    done
-    sleep 0.01
-    if [ -z "$(psql -l | grep db | grep developer)" ]; then
-      sleep 0.3
-      psql -c 'ALTER DATABASE db OWNER TO developer;'
-      sleep 0.3
-    fi
-    exit
-    ;;
+  case $1 in # Command dispatch ***********************************************
 
   run)
     shift
-    [ ! -f bin/start_openerp ] || [ ! -f parts/odoo/setup.py ] && export FROM_BASH=true && ak build
+    [ ! -f bin/start_openerp ] || [ ! -f parts/odoo/setup.py ] && \
+    export FROM_BASH=true && ak build
     ak wait_postgres
     python bin/start_openerp "$@"
     ;;
@@ -141,15 +151,17 @@ else # when we are inside the container
   build)
     shift
 
-    if [ ! -d /workspace/parts/odoo ]; then
+    if [ ! -d parts/odoo ]; then
     cat<<EOF
 
-      WARNING you didn't set any valid existing odoo repo in your buildout.dev.cfg odoo-directory
-      if you continue the recipe will do a FULL CLONE of Odoo into this directory
-      this clone will download ~400 Mo and can take a while...
+      WARNING you didn't set any valid existing odoo repo in your
+      buildout.dev.cfg odoo-directory.
+      If you continue, the recipe will do a FULL CLONE of Odoo into this
+      directory, this clone will download ~400 Mo and can take a while...
 
-      Alternatively you can abort and close the container and set a valid existing odoo-directory
-      in buildout.dev.cfg if you already have some with the right branch on your computer.
+      Alternatively you can abort and close the container and set a valid
+      existing odoo-directory in buildout.dev.cfg if you already have some
+      with the right branch on your computer.
 
       will now clone odoo...
 
@@ -157,11 +169,14 @@ EOF
     fi
 
     echo "building project with Anybox Buildout recipe..."
-    python bin/buildout "$@" "-c" "buildout.dev.cfg" \
-    "buildout:eggs-directory=$eggs_dir" \
-    "buildout:openerp-downloads-directory=/.devstep/addons/voodoo/downloads" \
-    "buildout:develop-eggs-directory=/.devstep/addons/voodoo/develop-eggs" \
-    "openerp:options.db_user=developer" "openerp:options.db_name=db" "openerp:options.data_dir=.filestore"
+    if [ -d /etc/service/postgresql ]; then
+      python bin/buildout "$@" "-c" "$BUILDOUT" "buildout:eggs-directory=$eggs_dir" \
+      "buildout:openerp-downloads-directory=/.devstep/addons/voodoo/downloads" \
+      "buildout:develop-eggs-directory=/.devstep/addons/voodoo/develop-eggs" \
+      "openerp:options.db_user=$DOCKER_USER" "openerp:options.db_name=db" "openerp:options.data_dir=.filestore"
+    else
+      python bin/buildout "$@" "-c" "$BUILDOUT" "buildout:eggs-directory=$eggs_dir"
+    fi
     ;;
 
   up)
@@ -187,6 +202,24 @@ EOF
     fi
     ;;
 
+  wait_postgres)
+    [ ! -d /etc/service/postgresql ] && exit
+    [ -f /.devstep/log/postgresql.log ] && r=$(grep "ready to accept connections" /.devstep/log/postgresql.log)
+    [ -z "$r" ] && echo "waiting for Postgresql embedded server to start..."
+    while [ -z "$r" ]
+    do
+      sleep 0.1
+      [ -f  /.devstep/log/postgresql.log ] && r=$(grep "ready to accept connections" /.devstep/log/postgresql.log)
+    done
+    sleep 0.01
+    if [ -z "$(psql -l | grep db | grep $DOCKER_USER)" ]; then
+      sleep 0.3
+      psql -c "ALTER DATABASE db OWNER TO $DOCKER_USER;"
+      sleep 0.3
+    fi
+    exit
+    ;;
+
   help)
     cat<<EOF
 
@@ -197,14 +230,11 @@ EOF
     ;;
 
   *)
-    [ ! -z "$1" ] && api=true
+    [ ! -z "$1" ] && exec ssh "$SSH_USER@$SERVER" "$@"
     ;;
 
   esac
 
+
+  [ "$FROM_BASH" != true ] && export FROM_BASH=true && exec /bin/bash
 fi
-
-
-[ "$1" = "api" ] && args="help" || args="$@"
-[ "$api" = true ] && exec ssh "$SSH_USER@$SERVER" "$args"
-[ "$FROM_BASH" != true ] && [ "$in_container" = true ] && export FROM_BASH=true && exec /bin/bash
